FROM alpine:latest
MAINTAINER "The Packer Team <packer@hashicorp.com>"

ENV PACKER_VERSION=0.0.15
ENV PACKER_SHA256SUM=94709d4ad196ad7565f96c9a34871e42b7ef39664533967132fbac78f7ccb38f

RUN apk add --update git bash wget openssl

ADD https://packer-release-staging.s3.us-east-2.amazonaws.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip ./
ADD https://packer-release-staging.s3.us-east-2.amazonaws.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_SHA256SUMS ./

RUN sed -i '/.*linux_amd64.zip/!d' packer_${PACKER_VERSION}_SHA256SUMS
RUN sha256sum -cs packer_${PACKER_VERSION}_SHA256SUMS
RUN unzip packer_${PACKER_VERSION}_linux_amd64.zip -d /bin
RUN rm -f packer_${PACKER_VERSION}_linux_amd64.zip

ENTRYPOINT ["/bin/packer"]
