FROM golang:alpine
LABEL maintainer="The Packer Team <packer@hashicorp.com>"

ENV PACKER_DEV=1

RUN apk add --no-cache git bash openssl ca-certificates
RUN go get github.com/mitchellh/gox
RUN go get github.com/krantzinator/packer

WORKDIR $GOPATH/src/github.com/krantzinator/packer

RUN /bin/bash scripts/build.sh

WORKDIR $GOPATH
ENTRYPOINT ["bin/packer"]
